-- SCHEMA
create schema staging;

comment on schema staging is
    'Staging area for non-relational data before it is transformed and loaded into the research schema';

grant usage on schema staging to :ro_role, :rw_role;


-- TABLES
set search_path to staging;

create table enrollment (
    enrollment_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null,
    received timestamp with time zone not null default now(),
    processed timestamp with time zone
);

comment on table enrollment is 'Append-only set of enrollment documents';
comment on column enrollment.enrollment_id is 'Internal id of this enrollment document';
comment on column enrollment.document is 'Original JSON record';
comment on column enrollment.received is 'When the document was received';
comment on column enrollment.processed is 'When the document was loaded into the research schema, if not null.';

-- XXX TODO: index on processed is not null?
-- XXX TODO: index on id, revision, participant, … in document?

grant select on enrollment to :ro_role, :rw_role;
grant insert on enrollment to :rw_role;
