-- Deploy seattleflu/schema:receiving/scan to pg
-- requires: receiving/schema
-- requires: citext

begin;

set local search_path to receiving, public;

create table scan_set (
    scan_set_id integer primary key generated by default as identity,
    received timestamp with time zone not null default now()
);

comment on table scan_set is 'A set of scanned barcodes';
comment on column scan_set.scan_set_id is 'Internal id of this scan set';
comment on column scan_set.received is 'When the scan set was received';


create table collection (
	collection_barcode citext primary key
        constraint collection_barcode_is_eight_hex_digits
            check (collection_barcode similar to '[0-9a-f]{8}')
);

comment on column collection.collection_barcode is E'Barcode (a CualID) applied to collection tubes for all prospective enrollment (community and clinical) and retrospective collection of residual clinical samples from Seattle Children\'s.  Does not exist for retrospective collection of residual clinical samples from the UW Medicine system.';


create table sample (
	sample_barcode citext primary key
        constraint sample_barcode_is_eight_hex_digits
            check (sample_barcode similar to '[0-9a-f]{8}'),
	collection_barcode citext unique references collection(collection_barcode),
	scan_set_id integer not null references scan_set(scan_set_id)
);

comment on column sample.sample_barcode is 'Barcode (a CualID) applied to all aliquot tubes identifying them as a single logical study sample.';


create table aliquot (
	aliquot_barcode integer primary key,
	sample_barcode citext not null references sample(sample_barcode)
);

comment on column aliquot.aliquot_barcode is 'Barcode (a number) identifying an individual aliquot (e.g. from Thermo Matrix tubes) of a sample.';

commit;
