-- Deploy seattleflu/schema:warehouse/consensus-genome to pg
-- requires: warehouse/sample
-- requires: warehouse/sequence-read-set
-- requires: warehouse/organism

begin;

set local search_path to warehouse;

create table consensus_genome (
    consensus_genome_id integer primary key generated by default as identity,
    sample_id integer references sample (sample_id) not null,
    organism_id integer references organism (organism_id) not null,
    sequence_read_set_id integer references sequence_read_set (sequence_read_set_id),
    details jsonb,
    constraint genome_has_unique_combination_of_sample_organism_sequence_reads
        unique (sample_id, organism_id, sequence_read_set_id)
);

comment on table consensus_genome is
    'A representation of a whole consensus genome for an organism extracted from a sample that may have been generated from a sequence read set';

comment on column consensus_genome.consensus_genome_id is
    'Internal id for this consensus genome';

comment on column consensus_genome.sample_id is
    'The sample from which this consensus genome was extracted';

comment on column consensus_genome.organism_id is
    'The organism that this consensus genome belongs to';

comment on column consensus_genome.sequence_read_set_id is
    'The sequence read set that was used to generate the consensus genome; This may be null if the genome is from an external source';

comment on column consensus_genome.details is
    'Additional information about this consensus genome which does not have a place in the relational schema';

create index consensus_genome_sample_id_idx on consensus_genome (sample_id);
create index consensus_genome_organism_id_idx on consensus_genome (organism_id);
create index consensus_genome_sequence_read_set_id_idx on consensus_genome (sequence_read_set_id);
create index consensus_genome_details_idx on consensus_genome using gin (details jsonb_path_ops);
create unique index genome_has_unique_sample_organism_when_sequence_reads_null on consensus_genome (sample_id, organism_id) where sequence_read_set_id is null;


commit;
