-- Deploy seattleflu/schema:warehouse/genomic_sequence to pg
-- requires: warehouse/genome

begin;

set local search_path to warehouse;

create table genomic_sequence (
    genomic_sequence_id integer primary key generated by default as identity,
    identifier text not null unique,
    segment text not null,
    seq text not null,
    genome_id integer references genome (genome_id) not null,
    details jsonb,
    constraint one_genomic_sequence_per_segment_per_genome
        unique(segment, genome_id)
);

comment on table genomic_sequence is
    'A genomic sequence from a genome. There may be multiple sequences per genome if the genome is segmented (e.g. Influenza genomes)';

comment on column genomic_sequence.genomic_sequence_id is
    'Internal id of this genomic sequence';

comment on column genomic_sequence.identifier is
    'An external, unqiue identifier for this genomic sequence';

comment on column genomic_sequence.segment is
    'The segment of the genome that this genomic sequence represents';

comment on column genomic_sequence.seq is
    'A succession of letters indicating the order of nucleotides of the genomic sequence';

comment on column genomic_sequence.genome_id is
    'The genome that this genomic sequence belongs to';

comment on column genomic_sequence.details is
    'Additional information about this genomic sequence which does not have a place in the relational schema';

create index genomic_sequence_segment_idx on genomic_sequence (segment);
create index genomic_sequence_seq_idx on genomic_sequence (seq);
create index genomic_sequence_genome_id_idx on genomic_sequence (genome_id);
create index genomci_sequence_details_idx on genomic_sequence using gin (details jsonb_path_ops);

commit;
