-- Deploy seattleflu/schema:warehouse/genome to pg
-- requires: warehouse/sample
-- requires: warehouse/sequence-read-set
-- requires: warehouse/organism

begin;

set local search_path to warehouse;

create table genome (
    genome_id integer primary key generated by default as identity,
    sample_id integer references sample (sample_id) not null,
    organism_id integer references organism (organism_id) not null,
    sequence_read_set_id integer references sequence_read_set (sequence_read_set_id),
    details jsonb,
    constraint genome_has_unique_combination_of_sample_organism_sequence_reads
        unique (sample_id, organism_id, sequence_read_set_id)
);

comment on table genome is
    'A representation of a whole genome for an organism extracted from a sample that may have been generated from a sequence read set';

comment on column genome.genome_id is
    'Internal id for this genome';

comment on column genome.sample_id is
    'The sample from which this genome was extracted';

comment on column genome.organism_id is
    'The organism that this genome belongs to';

comment on column genome.sequence_read_set_id is
    'The sequence read set that was used to generate the genome; This may be null if the genome is from an external source';

comment on column genome.details is
    'Additional information about this genome which does not have a place in the relational schema';

create index genome_sample_id_idx on genome (sample_id);
create index genome_organism_id_idx on genome (organism_id);
create index genome_sequence_read_set_id_idx on genome (sequence_read_set_id);
create index genome_details_idx on genome using gin (details jsonb_path_ops);


commit;
