-- Deploy seattleflu/schema:warehouse/identifier to pg
-- requires: warehouse/schema
-- requires: uuid-ossp

begin;

set local role id3c;

-- Sets of identifiers, e.g. samples, collections-seattleflu.org, kits-fluathome.org, etc.
create table warehouse.identifier_set (
    identifier_set_id integer primary key generated by default as identity,
    name text not null unique,
    description text
);

comment on table warehouse.identifier_set is
    'A conceptual group of identifiers used for a common purpose';

comment on column warehouse.identifier_set.identifier_set_id is
    'Internal id of this identifier set';

comment on column warehouse.identifier_set.name is
    'The well-known, unique name of the set';

comment on column warehouse.identifier_set.description is
    'A plain text description of the purpose and usage of this set';


-- Universally unique identifiers and their CualID barcodes
create table warehouse.identifier (
    uuid uuid primary key default uuid_generate_v4(),

    -- Default will be provided by trigger in order to reference the uuid column.
    barcode citext not null unique
        constraint identifier_barcode_length
            check (length(barcode) = 8),

    identifier_set_id integer not null references warehouse.identifier_set(identifier_set_id),

    generated timestamp with time zone not null default now(),

    constraint identifier_barcode_is_suffix_of_uuid
        check (uuid::citext like '%' || barcode)
);

comment on table warehouse.identifier is
    'Globally unique ids and their CualID barcodes, used for tracking physical things';

comment on column warehouse.identifier.uuid is
    'UUIDv4 that should be used in programmatic and downstream data processing';

comment on column warehouse.identifier.barcode is
    'Short suffix of UUID (CualID) used as a tracking barcode';

comment on column warehouse.identifier.identifier_set_id is
    'Internal id of the set of identifiers this identifier belongs to';

comment on column warehouse.identifier.generated is
    'When this identifier was generated';

commit;
