-- Deploy seattleflu/schema:warehouse/individual to pg
-- requires: warehouse/assigned-sex

begin;

set local role id3c;

set local search_path to warehouse;

create table individual (
    individual_id integer primary key generated by default as identity,
    identifier text not null unique,
    sex assigned_sex,
    details jsonb
);

create index individual_details_idx on individual using gin (details jsonb_path_ops);

comment on table individual is 'A single, real person (or other member of a population)';
comment on column individual.individual_id is 'Internal id of this individual';
comment on column individual.identifier is 'External identifier for this individual (e.g. study participant id)';
comment on column individual.sex is 'Sex assigned at birth';
comment on column individual.details is 'Additional information about this individual which does not have a place in the relational schema';

commit;
