-- Deploy seattleflu/schema:warehouse/kit to pg
-- requires: warehouse/encounter
-- requires: warehouse/sample

begin;

set local search_path to warehouse;

create table kit (
    kit_id integer primary key generated by default as identity,
    identifier text not null unique,
    encounter_id integer references encounter (encounter_id)
        constraint kit_references_not_null check (
            encounter_id is not null
            or (encounter_id is null
                and (rdt_sample_id is not null
                     or utm_sample_id is not null))
        ),
    rdt_sample_id integer references sample (sample_id),
    utm_sample_id integer references sample (sample_id),
    details jsonb
);

comment on table kit is 'A self-test kit connected to an encounter and 2 different samples';
comment on column kit.kit_id is 'Internal id of this kit';
comment on column kit.identifier is 'A unique exteranl identifier assigned to this kit';
comment on column kit.encounter_id is 'The encounter where this kit was used';
comment on column kit.rdt_sample_id is 'The sample collected from the residual RDT extractant';
comment on column kit.utm_sample_id is 'The sample collected from the second swab';
comment on column kit.details is 'Additional information about this kit which does not have a place in the relational schema';

create index kit_encounter_id_idx on kit (encounter_id);
create index kit_rdt_sample_id_idx on kit (rdt_sample_id);
create index kit_utm_sample_id_idx on kit (utm_sample_id);
create index kit_details_idx on kit using gin (details jsonb_path_ops);

commit;
