-- Deploy seattleflu/schema:warehouse/organism to pg
-- requires: hstore
-- requires: ltree
-- requires: warehouse/schema

begin;

set local role id3c;

set local search_path to warehouse, public;

create table organism (
    organism_id integer primary key generated by default as identity,
    lineage ltree not null unique,
    identifiers hstore,
    details jsonb
);

comment on table organism is
    'Hierarchical classification of taxa';

comment on column organism.organism_id is
    'Interal id of this organism; use only for internal foreign keys';

comment on column organism.lineage is
    'Label tree of ancestors with this organism as the leaf/final label';

comment on column organism.identifiers is
    'Key-value pairs of external identifiers (i.e. dbxrefs) for this organism; keys should use well-known database or ontology prefix (e.g. NCBITaxon)';

comment on column organism.details is
    'Additional information about this organism which does not have a place in the relational schema';

create index organism_lineage_idx on organism using gist (lineage);
create index organism_identifiers_idx on organism using gist (identifiers);
create index organism_details_idx on organism using gin (details jsonb_path_ops);

commit;
