-- Deploy seattleflu/schema:warehouse/sequence-read-set to pg
-- requires: warehouse/sample
-- requires: functions/array_distinct

begin;

set local search_path to warehouse, public;

create table sequence_read_set (
    sequence_read_set_id integer primary key generated by default as identity,
    sample_id integer references sample (sample_id) not null,
    urls text[] not null
        constraint sequence_read_set_urls_is_not_empty
            check(urls <> '{}')
        constraint sequence_read_set_urls_contains_no_nulls
            check (array_position(urls, null) is null)
        constraint sequence_read_set_urls_are_unique
            check (urls = array_distinct(urls)),
    details jsonb
);

comment on table sequence_read_set is
    'A set of references to sequence reads from an individual sample';

comment on column sequence_read_set.sequence_read_set_id is
    'Internal id of this set of sequence reads';

comment on column sequence_read_set.sample_id is
    'The sample from which the sequence reads were generated';

comment on column sequence_read_set.urls is
    'External object store urls that hold the sequence reads';

comment on column sequence_read_set.details is
    'Additional information about this sequence read set which does not have a place in the relational schema';

create index sequence_read_set_sample_id_idx on sequence_read_set (sample_id);
create index sequence_read_set_urls_idx on sequence_read_set using gin (urls);
create index sequence_read_set_details_idx on sequence_read_set using gin (details jsonb_path_ops);

commit;
