-- Deploy seattleflu/schema:warehouse/target to pg
-- requires: warehouse/schema

begin;

set search_path to warehouse;

create table target (
    target_id integer primary key generated by default as identity,
    identifier text not null unique,
    control boolean not null
);

-- We considered adding human-readable columns (target name, target description) to the table.
--   We ultimately decided that for now, this table does not need to serve that purpose. We can optionally
--   add a taxa or organism table down the road which would contain text details about the contents of 
--   the target table. 

comment on table target is 'A thing (e.g. pathogen) that can be detected in presence-absence testing';
comment on column target.identifier is 'An identifier assigned to this target by the testing center, assumed to be stable and unique';
comment on column target.control is 'A boolean indicating whether target is a control';

commit;
