-- Deploy seattleflu/schema:receiving/consensus-genome to pg
-- requires: receiving/schema

begin;

set local search_path to receiving;

create table consensus_genome (
    consensus_genome_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null
        constraint consensus_genome_document_is_object
            check (json_typeof(document) = 'object'),

    received timestamp with time zone not null default now(),

    processing_log jsonb not null default '[]'
        constraint consensus_genome_processing_log_is_array
            check (jsonb_typeof(processing_log) = 'array')
);

comment on table consensus_genome is
    'Append-only set of consensus genome documents';

comment on column consensus_genome.consensus_genome_id is
    'Internal id of this record';

comment on column consensus_genome.document is
    'Original JSON document';

comment on column consensus_genome.received is
    'When the document was received';

comment on column consensus_genome.processing_log is
    'Event log recording details of ETL into the warehouse';

commit;
