-- Deploy seattleflu/schema:receiving/longitudinal to pg
-- requires: receiving/schema

begin;

set local search_path to receiving;

create table longitudinal (
    longitudinal_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null
        constraint longitudinal_document_is_object
            check (json_typeof(document) = 'object'),

    received timestamp with time zone not null default now(),

    processing_log jsonb not null default '[]'
        constraint longitudinal_processing_log_is_array
            check (jsonb_typeof(processing_log) = 'array')
);

comment on table longitudinal is
    'Append-only set of longitudinal documents';

comment on column longitudinal.longitudinal_id is
    'Internal id of this record';

comment on column longitudinal.document is
    'JSON document created from a pre-processed Excel file';

comment on column longitudinal.received is
    'When the document was received';

comment on column longitudinal.processing_log is
    'Event log recording details of ETL into the warehouse';

commit;
