-- Deploy seattleflu/schema:receiving/presence-absence to pg
-- requires: receiving/schema

begin;

set local search_path to receiving;

create table presence_absence (
    presence_absence_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null
        constraint presence_absence_document_is_object
            check (json_typeof(document) = 'object'),

    received timestamp with time zone not null default now(),

    processing_log jsonb not null default '[]'
        constraint presence_absence_processing_log_is_array
            check (jsonb_typeof(processing_log) = 'array')
);

comment on table presence_absence is
    'Append-only set of presence/absence documents';

comment on column presence_absence.presence_absence_id is
    'Internal id of this record';

comment on column presence_absence.document is
    'Original JSON document';

comment on column presence_absence.received is
    'When the document was received';

comment on column presence_absence.processing_log is
    'Event log recording details of ETL into the warehouse';

commit;
