-- Deploy seattleflu/schema:receiving/redcap-det to pg
-- requires: receiving/schema

begin;

set local search_path to receiving;

create table redcap_det (
    redcap_det_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null
        constraint redcap_det_document_is_object
            check (json_typeof(document) = 'object'),

    received timestamp with time zone not null default now(),

    processing_log jsonb not null default '[]'
        constraint redcap_det_processing_log_is_array
            check (jsonb_typeof(processing_log) = 'array')
);

comment on table redcap_det is
    'Append-only set of REDCap DET request data documents';

comment on column redcap_det.redcap_det_id is
    'Internal id of this record';

comment on column redcap_det.document is
    'JSON document created from REDCap DET request data';

comment on column redcap_det.received is
    'When the document was received';

comment on column redcap_det.processing_log is
    'Event log recording details of ETL into the warehouse';

commit;
