-- Deploy seattleflu/schema:receiving/sequence-read-set to pg
-- requires: receiving/schema

begin;

set search_path to receiving;

create table sequence_read_set (
    sequence_read_set_id integer primary key generated by default as identity,

    -- Using json not jsonb because we want to keep the exact text around for
    -- debugging purposes.
    document json not null
        constraint sequence_read_set_document_is_object
            check (json_typeof(document) = 'object'),

    received timestamp with time zone not null default now(),

    processing_log jsonb not null default '[]'
        constraint sequence_read_set_processing_log_is_array
            check (jsonb_typeof(processing_log) = 'array')
);

comment on table sequence_read_set is
    'Append-only set of references to sequence reads';

comment on column sequence_read_set.sequence_read_set_id is
    'Internal id of this record';

comment on column sequence_read_set.document is
    'Original JSON document';

comment on column sequence_read_set.received is
    'When the read set was received';

comment on column sequence_read_set.processing_log is
    'Event log recording details of ETL into the warehouse';

commit;
